name: terraform-new-workspace
description: Create a new terraform workspace
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace
    required: true
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:c839fa1fb34369e1230ba77891e0a1ba30a8f52e0b42d8335d860f313f42b09e
  entrypoint: /entrypoints/new-workspace.sh

branding:
  icon: globe
  color: purple
